### ISSUE TITLE
(enhancement) Ability to retrieve the set of user defined variables from a given config

### ISSUE THREAD

**Issue by plermant** [akamai/cli-property#10]
Whenever a configuration is cloned to be ported to a different environment (say QA to Prod), system needs to know the user defined variables (PM_USER) in the source config so it can make sure to update them all. Request is to have a  configKit call that would list all the user defined  variables found in a given config:
e.g. akamaiProperty list --variables configName
which would return a json structure similar to the input to "modify --variables"
[{"name": "PMUSER_LOGIN_ORIGIN","value": "Testing","description": "checking variable use", "sensitive": true}]

**Comment by roryhewitt** [comment]
This can currently be done, but a lot of header lines are included in the output. For example, try this:

`./akamaiProperty retrieve --variables june12m`

which retrieves something like the following:

Retrieving june12m
... retrieved rules formats: 625.068ms
Initializing property cache
Init PropertyManager cache (hostnames and property list)
... retrieving list of Group Ids
... retrieving properties from 17 groups
... no permissions, ignoring  {ctr_1-1U72M7 : grp_24708}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_24709}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_54598}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_24703}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_63900}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_24707}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_24705}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_64634}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_48393}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_24710}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_64635}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_63903}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_82575}
... no permissions, ignoring  {ctr_3-1AZ95HC : grp_54598}
... retrieving Hosts from 31 properties
Init PropertyManager cache: 11868.404ms
... no permissions, ignoring  {ctr_1-1U72M7 : grp_24710}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_63903}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_64635}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_54598}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_82575}
... no permissions, ignoring  {ctr_3-1AZ95HC : grp_54598}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_24707}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_24703}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_48393}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_64634}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_63900}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_24709}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_24705}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_24708}
Retrieving variables for june12m v1
... retrieving property (june12m) v1
... retrieving: 3811.752ms
[
  {
    "name": "PMUSER_CSP_HEADER",
    "value": "",
    "description": "CSP header from origin",
    "hidden": true,
    "sensitive": false
  },
...

The request is really simply to remove all the headers, so all that is returned is the JSON itself.

Ideally, perhaps a --verbose flag, to return (or not) the header information?

**Comment by synedra** [comment]
akamai property retrieve host.name.com --variables
