### ISSUE TITLE
Ability to create a new version of a given config.

### ISSUE THREAD

**Issue by plermant** [akamai/cli-property#11]
Ability to create a new version of a given config.
e.g. akamaiProperty create --version configFile

if '--version' is absent or point to a version that does not exist, a new version is created from the latest available. '--version' could also take 'staging' or 'production' value to create a new version based off production or staging

**Comment by plermant** [comment]
Can be closed, I opened https://github.com/akamai-open/akamaiconfigkit-public/issues/17 instead, sorry for misunderstanding.

**Comment by orderedchaosdev** [comment]
This is still important because if you use update it generates the host list from the latest version inside the property rather than the production version.
