### ISSUE TITLE
Undefined property name parameter in Search Command

### ISSUE THREAD

**Issue by gfirem** [akamai/cli-property#113]
The search command return error with undefined property name parameter.

**Comment by synedra** [comment]
I just fixed this last week.  How was it broken?  Hard coding it positionally isn’t the right answer.

**Comment by synedra** [comment]
Again, not sure what problem you're fixing here.  There's no test case demonstrating the problem, and I suspect that it's actually a documentation error.  This should not be integrated.

**Comment by gfirem** [comment]
@synedra, the last version of the code in master has a typo error and the search command is not working. This issue don't appear in the test because they only test the server request, not the command line.

**Comment by synedra** [comment]
Please include an example of a broken command so I can test it.

**Comment by gfirem** [comment]
if you run `npm start search test123` the command will search form an `undefined` value instead of `test123` and finish the command with an **error** coming from the server.

**Comment by synedra** [comment]
That's not how you use the CLI.

What do you get with 'akamai property search abc123'?

**Comment by gfirem** [comment]
@synedra the command works with an old version i got installed, but after the update the behavior is the same as when triggering `npm start search test123 ` over the repository.
