### ISSUE TITLE
Creating a new config from file does not set cpcode

### ISSUE THREAD

**Issue by plermant** [akamai/cli-property#12]
Following command created a new config file ok, however the cpcode field, when viewed from UI, is left blank, although a valid cpcode is furnished in the request:

akamaiProperty create p11 --file ./dump3 --edgehostname devopsdemo1.edgekey.net --hostnames p11.com --origin originp11.com --group grp_101490 --contract ctr_1-1U72M7 --cpcode 131454

Output:

Creating new property p11
... retrieving list of Group Ids
... retrieving list of Products for this contract
... retrieving list of Products for this contract
Creating property config p11
... creating: 5038.017ms
Init PropertyManager cache (hostnames and property list)
... retrieving list of Group Ids
... retrieving properties from 17 groups
... no permissions, ignoring  {ctr_1-1U72M7 : grp_24703}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_63900}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_24708}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_63903}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_24710}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_24709}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_82575}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_64635}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_48393}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_64634}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_24707}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_24705}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_54598}
... no permissions, ignoring  {ctr_3-1AZ95HC : grp_54598}
... retrieving Hosts from 8 properties
Init PropertyManager cache: 6756.884ms
Retrieving [object Object] v1
... retrieving property (prp_378174) v1
... retrieving: 3694.863ms
... updating property (p11) v1
... updating: 12410.985ms
Checking for existing edge hostname
... checking edge hostnames: 267.979ms
Updating property hostnames
Adding hostname p11.com
... updating hostname: 8782.392ms

**Comment by synedra** [comment]
Completed, ran regression tests.
