### ISSUE TITLE
add a parameter alias --edgerc to allow indicating the location of the .edgerc file

### ISSUE THREAD

**Issue by javiergarza** [akamai/cli-property#131]
Can we please add an  --edgerc parameter which does the same as --config ? (the CLI syntax guide suggest having --edgerc and --section)

**Comment by joaquin-gimenez** [comment]
@dshafik @synedra how should we show the alias in on the help command? we don't have space to show a text like "alternatively use --edgerc" so we would have to add another line with almost the same content as in the attachment.
<img width="775" alt="screen shot 2019-02-22 at 3 42 42 pm" src="https://user-images.githubusercontent.com/1648222/53263738-07401280-36b9-11e9-9bf6-3cb251cb1032.png">
