### ISSUE TITLE
Trying to delete property (akamai property delete someConfig) fails if property not active in Staging and Prod

### ISSUE THREAD

**Issue by angelnogueras** [akamai/cli-property#137]
Could it be possible to check if property is active to only deactivate in case it is before deleting?

**Comment by synedra** [comment]
Joaquin,

I don't see the chance to merge this into the code base.  Can you make a PR and get it ready to release?  Need this resolved quickly.

**Comment by synedra** [comment]
There's no PR here to merge.

**Comment by joaquin-gimenez** [comment]
@synedra the pr that fixes this is https://github.com/akamai/cli-property/pull/143/files
