### ISSUE TITLE
Errors related to SureRoute behavior

### ISSUE THREAD

**Issue by angelnogueras** [akamai/cli-property#139]
Creating a property from scratch and setting sureroute test object with:
`akamai property modify $PROPERTY_NAME --surerouteto $SR_TO`

the generated configuration shows several errors:

```
"errors": [
    {
      "type": "https://problems.luna.akamaiapis.net/papi/v0/validation/attribute_required",
      "errorLocation": "#/rules/children/0/behaviors/4/options/enableCustomKey",
      "detail": "The Race Result Key option on the `SureRoute` behavior is required."
    },
    {
      "type": "https://problems.luna.akamaiapis.net/papi/v0/validation/unknown_attribute",
      "errorLocation": "#/rules/children/0/behaviors/4/options/sr_stat_key_mode",
      "detail": "The behavior '`SureRoute`' does not have sr_stat_key_mode."
    },
    {
      "type": "https://problems.luna.akamaiapis.net/papi/v0/validation/unknown_attribute",
      "errorLocation": "#/rules/children/0/behaviors/4/options/sr_test_object_url",
      "detail": "The behavior '`SureRoute`' does not have sr_test_object_url."
    }
  ]
```

If we compare the json generated by "akamai property" with another generated in Luna:

LUNA GENERATED:
```
{
    "name": "sureRoute",
    "options": {
        "enabled": true,
        "forceSslForward": false,
        "raceStatTtl": "30m",
        "testObjectUrl": "/akamai/testobject.html",
        "toHostStatus": "INCOMING_HH",
        "type": "PERFORMANCE",
        "enableCustomKey": false
    }
},
```

AKAMAI PROPERTY CLI:
```
{
  "name": "sureRoute",
  "options": {
    "enabled": true,
    "forceSslForward": false,
    "raceStatTtl": "30m",
    "testObjectUrl": "/akamai/testobject.html",
    "toHostStatus": "INCOMING_HH",
    "type": "PERFORMANCE",
    "sr_stat_key_mode": "default",
    "sr_test_object_url": "/akamai/sureroute-testobject.html"
  }
},
```

It seems that:
- "sr_test_object_url" should be removed in favor of the existing "testObjectUrl"
- "enableCustomKey" is required, defaulting to false
- In case "enableCustomKey" is true, the stat key should be in a variable "customStatKey"

This is another valid example from Luna choosing custom stat key:
```
{
                        "name": "sureRoute",
                        "options": {
                            "enabled": true,
                            "forceSslForward": false,
                            "raceStatTtl": "30m",
                            "testObjectUrl": "/akamai/testobject.html",
                            "toHostStatus": "INCOMING_HH",
                            "type": "PERFORMANCE",
                            "enableCustomKey": true,
                            "customStatKey": "blablabla.bla.bla"
                        }
                    },
```

**Comment by joaquin-gimenez** [comment]
@angelnogueras what is the value of $SR_TO so that i can replicate the error. how can also test to retrieve the output you mentioned for both luna and akamai cli

**Comment by angelnogueras** [comment]
@joaquin-gimenez, the value of SR_TO is a path, I used "/akamai/testobject.html".
I got the output from akamai cli with `akamai property retrieve $PROPERTY_NAME`
Then I created a different configuration via Luna, both of them with product type "Fresca" (product ID "prd_Fresca").
Also, you can take a look at the schema of a "Fresca" configuration using calling ":/papi/v1/schemas/products/prd_Fresca/latest", where the section covering SureRoute is:

```
        "sureRoute" : {
          "type" : "object",
          "properties" : {
            "name" : {
              "enum" : [ "sureRoute", "sureroute" ]
            },
            "uuid" : {
              "type" : "string"
            },
            "templateUuid" : {
              "type" : "string"
            },
            "options" : {
              "type" : "object",
              "properties" : {
                "enabled" : {
                  "enum" : [ false, true ],
                  "default" : true
                },
                "type" : {
                  "enum" : [ "PERFORMANCE", "CUSTOM_MAP" ],
                  "default" : "PERFORMANCE"
                },
                "customMap" : {
                  "type" : "string"
                },
                "testObjectUrl" : {
                  "type" : "string"
                },
                "toHostStatus" : {
                  "enum" : [ "INCOMING_HH", "OTHER" ],
                  "default" : "INCOMING_HH"
                },
                "toHost" : {
                  "type" : "string"
                },
                "raceStatTtl" : {
                  "$ref" : "#/definitions/catalog/option_types/duration",
                  "default" : "30m"
                },
                "forceSslForward" : {
                  "enum" : [ false, true ],
                  "default" : false
                },
                "enableCustomKey" : {
                  "enum" : [ false, true ],
                  "default" : false
                },
                "customStatKey" : {
                  "type" : "string",
                  "default" : ""
                }
              }
            },
            "locked" : {
              "type" : [ "null", "boolean" ]
            }
          }
        },
```

where you can see that both "sr_stat_key_mode" and "sr_test_object_url" doesn't exist.

**Comment by joaquin-gimenez** [comment]
@angelnogueras thanks for the response. 
I'm trying to update sureRoute testObjectUrl with httpie command "http --auth-type edgegrid -a papi: PUT  :/papi/v0/properties/prp_508686/versions/341/rules contractId==ctr_C-1FRYVV3 groupId==grp_95357 < fileName"

after running the command the response related to sureroute is: 
"children": [
            {
                "behaviors": [],
                "children": [],
                "criteria": [],
                "criteriaMustSatisfy": "all",
                "name": "sureRoute"
            }
        ]
As you can see "testObjectUrl is not being saved"
this is part of the file i'm updating the property from:
"rules" : {
    "name" : "default",
    "children" : [{
      "name": "sureRoute",
      "options" : {
        "testObjectUrl": "/akamai/testobject.html"
      }
    }],
    "behaviors" : [{
      "name" : "originCharacteristics",
      "options" : {
        "authenticationMethod" : "AUTOMATIC",
        "country" : "UNKNOWN",
        "authenticationMethodTitle" : ""
      }
    }, {

I feel there is a syntax error compared to the schema but can't figure it out, do you see anything wrong on my schema sent?
cheers

**Comment by angelnogueras** [comment]
Hi @joaquin-gimenez,
I have never tried to upload just the element with name and options.testObjectUrl.
As far as I understand, Luna generates the XML/JSON required for an object, so maybe you could try with the whole sureRoute element as is created in a property using the Luna UI:

```
{
            "name": "sureRoute",
            "options": {
              "enabled": true,
              "forceSslForward": false,
              "raceStatTtl": "30m",
              "testObjectUrl": "/akamai/testobject.html",
              "toHostStatus": "INCOMING_HH",
              "type": "PERFORMANCE",
              "enableCustomKey": false
            }
          },
```

Also, the PAPI Feature Catalog ref can help here:
https://developer.akamai.com/api/core_features/property_manager/vlatest.html#sureroute

**Comment by joaquin-gimenez** [comment]
@angelnogueras I'm trying to replicate the error you showed:
"errors": [
    {
      "type": "https://problems.luna.akamaiapis.net/papi/v0/validation/attribute_required",
      "errorLocation": "#/rules/children/0/behaviors/4/options/enableCustomKey",
      "detail": "The Race Result Key option on the `SureRoute` behavior is required."
    },
    {
      "type": "https://problems.luna.akamaiapis.net/papi/v0/validation/unknown_attribute",
      "errorLocation": "#/rules/children/0/behaviors/4/options/sr_stat_key_mode",
      "detail": "The behavior '`SureRoute`' does not have sr_stat_key_mode."
    },
    {
      "type": "https://problems.luna.akamaiapis.net/papi/v0/validation/unknown_attribute",
      "errorLocation": "#/rules/children/0/behaviors/4/options/sr_test_object_url",
      "detail": "The behavior '`SureRoute`' does not have sr_test_object_url."
    }
  ]

this error has to have been the response from creating the property and not the modify command "
akamai property modify $PROPERTY_NAME --surerouteto $SR_TO" as the corresponding block would only be run on create command.
Did you create the property from a version, file or cloned a property? please give me info on the create command and rules used. 
thanks again

**Comment by angelnogueras** [comment]
Hi @joaquin-gimenez 

I'm creating a property from scratch (starting from the product name "Fresca").
I tried to create the property with a single command but it always fails, so I split the process in several commands:

```
step "About to create property..."
akamai property --section $SECTION create $PROPERTY_NAME --cpcode $CPCODE \
  --contract $contract_id --group $group_id --product $product_id \
  --ruleformat $RULE_FORMAT

step "About to set CPCode..."
akamai property --section $SECTION modify $PROPERTY_NAME --cpcode $CPCODE

step "About to set hostname and edgehostname..."
akamai property --section $SECTION modify $PROPERTY_NAME --addhosts $HOSTNAME --edgehostname $EDGEHOSTNAME

step "About to set SRTO..."
akamai property --section $SECTION modify $PROPERTY_NAME --surerouteto $SR_TO

step "about to set Origin and Forward host header..."
akamai property --section $SECTION modify $PROPERTY_NAME --origin $ORIGIN --forward origin
```

Anyway, just in case it helps you, for my very use case (starting from scratch), I have been looking into the code and modify cli-property/src/website.js (around line 773):

```
                    if (behavior.name == "sureRoute") {
                        //ORIGINAL: if (!behavior.options.sr_stat_key_mode && !behavior.options.testObjectUrl) {
                        if (!behavior.options.enableCustomKey && !behavior.options.testObjectUrl) {
                            //ORIGINAL: behavior.options.sr_stat_key_mode = "default";
                            //ORIGINAL: behavior.options.sr_test_object_url = "/akamai/sureroute-testobject.html"
                            behavior.options.testObjectUrl = "/akamai/sureroute-testobject.html"
                            behavior.options.enableCustomKey = false;
                        }
                    }
```

hope that helps.

Regards,
