### ISSUE TITLE
(Urgent!) Can not make new config version base on a specify version

### ISSUE THREAD

**Issue by yuanchang-akm** [akamai/cli-property#144]
For example:
The latest version of the config is version 11
But we want to make a new version 12 based on version 8.
Even though we new --propver option to set a specify version 8.
The new version 12 will be made by copying version 11.

akamai property --config ./property_security_cpcode_cred.txt --section propertyandsecurityandcpcode modify suntory2.ksd.test.xyz --propver 8 --new

... searching propertyName for suntory2.ksd.test.xyz
... getting info for prp_512641
Creating new version for suntory2.ksd.test.xyz
... copy property (suntory2.ksd.test.xyz) v11
Command time: 0.089 min

**Comment by dshafik** [comment]
@yuanchang-akm this issue is fixed by #130 (which also fixes #77) and should be included in the next release. It will likely be a couple of weeks before that happens.

**Comment by yuanchang-akm** [comment]
@dshafik 
Could you please release it now?
Out customer is waiting for this function to manage their config.
This problem need to be solved as soon as possible.

**Comment by dshafik** [comment]
@yuanchang-akm please email me at dshafik@akamai.com to discuss this further.
