### ISSUE TITLE
wrong origin hostname set when creating a property out of a JSON rules file

### ISSUE THREAD

**Issue by javiergarza** [akamai/cli-property#146]
The origin gets set with the wrong hostname unless you indicate both the origin behavior within the JSON code and you pass the right hostname with the --origin parameter.

Bug 1# if you just indicate the origin hostname within the json rules, the origin hostname gets set but with the wrong hostname. 
Instructions to reproduce:
save the JSON code below in a file called rules1.json (you may need to update the values on "accountId", "contractId", and "groupId")
[rules1.json.txt](https://github.com/akamai/cli-property/files/3014163/rules1.json.txt) and then run the following command: 
akamai property --section papi-gssclinic create jgarza-launchpad9c --hostnames jgarza-launchpad9c.gssclinic.world-tour.akamaideveloper.net --edgehostname gssclinic.world-tour.akamaideveloper.net.edgesuite.net --file rules1.json --product prd_SP

The file created had the origin hostname: origin-jgarza-launchpad9c (although I indicated origin-chewaka.spacewalks.us on my rules1.json)

Bug 2# if you just indicate the origin hostname within the --origin parameter but don't include the origin behavior on rules.json the CLI would not show any errors, but the generated papi property won't have the origin behavior at all (you can't activate because of errors).
Instructions to reproduce:
save the JSON code below in a file called rules2.json (you may need to update the values on "accountId", "contractId", and "groupId")
[rules2.json.txt](https://github.com/akamai/cli-property/files/3014210/rules2.json.txt)
 and then run the following command: 
akamai property --section papi-gssclinic create jgarza-launchpad9c --hostnames jgarza-launchpad9c.gssclinic.world-tour.akamaideveloper.net --edgehostname gssclinic.world-tour.akamaideveloper.net.edgesuite.net --file rules2.json --product prd_SP

The file created had the origin hostname: origin-jgarza-launchpad9c (although I indicated origin-chewaka.spacewalks.us on my rules1.json)

**Comment by joaquin-gimenez** [comment]
@javiergarza on bug1 wouldn't it be the expected behavior that the flag --origin overrides the origin set on --file? I feel like --file is more generic than --origin

**Comment by javiergarza** [comment]
Yes, that’s correct. Parameter values should overwrite the JSON file (we shoud clarify this in the online doc)

**Comment by joaquin-gimenez** [comment]
@javiergarza ok, so we agree that bug1 is not a bug because it is behaving as expected.

**Comment by javiergarza** [comment]
#1 it is still a bug, the origin should be set right if you indicate it in the JSON and do NOT indicate the --origin parameter
