### ISSUE TITLE
cli-property not handling hostnames/edgehostnames

### ISSUE THREAD

**Issue by ghost** [akamai/cli-property#151]
MacBook-Pro-4:~ khunter$ akamai property create example.astronaut.training --hostnames example.astronaut.training --edgehostname example.astronaut.training.edgesuite.net --origin origin-web.spacewalk.tours --group grp_65092 --contract ctr_C-1FRYVV3
... retrieving list of Group Ids
... retrieving list of Products for this contract
Creating property config example.astronaut.training
... searching propertyName for example.astronaut.training
Creating new CPCode for property
MacBook-Pro-4:

The resulting property has no hostnames or edgehostnames.  Somehow it's falling out of the chain.  Let's fix this.

**Comment by joaquin-gimenez** [comment]
@synedra this issue will be fixed with pr #148
