### ISSUE TITLE
newcpcode doesn't work correctly

### ISSUE THREAD

**Issue by synedra** [akamai/cli-property#152]
When creating a new property, the *default* should be to create a new CPCode.  Even if someone wants to request a new CPCode they won't know what that code is, so the existing code does not work correctly.

Please make it so that:
* If someone creates a new property without a CPCode a new one is created
* If someone uses -newcpcode they do not have to give a CPCode as an argument (because it can't be set separately)

**Comment by synedra** [comment]
Note that even though it says "Creating new CPCode for property" it isn't actually added to the property.  This needs to be fixed.

**Comment by joaquin-gimenez** [comment]
@synedra 
If someone creates a new property without a CPCode a new one is created. _I can do this change_
If someone uses -newcpcode they do not have to give a CPCode as an argument (because it can't be set separately) - _On this point what is set from the flag --newcpcode 12313 is the cpcode name as attached, not the cpcode id. do you think it does not make sense to set a name by the user?_
<img width="794" alt="Screen Shot 2019-04-09 at 2 25 32 PM" src="https://user-images.githubusercontent.com/1648222/55821603-40e7a400-5ad4-11e9-8a2d-81d64fd09e00.png">

**Comment by synedra** [comment]
The name of the vocoders is fine.  Main problem here is that the cpcode is not associated with the property.

Kirsten

Sent from my iPhone

On Apr 9, 2019, at 10:34 AM, Joaquin Gimenez <notifications@github.com<mailto:notifications@github.com>> wrote:


@synedra<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_synedra&d=DwMFaQ&c=96ZbZZcaMF4w0F4jpN6LZg&r=Q1_WK8mWWUtQ5xZX1lcsIPCasN7Y3hsyzvEZltDs4Vs&m=8w34xv0sw36YDB2zASvG4cb-Vtyqdkrs3LSfmkamUpc&s=FELiED2meCFEEK4ucSCETWu-q43R6eSs9wfIpQdKyuQ&e=>
If someone creates a new property without a CPCode a new one is created. I can do this change
If someone uses -newcpcode they do not have to give a CPCode as an argument (because it can't be set separately) - On this point what is set from the flag --newcpcode 12313 is the cpcode name as attached, not the cpcode id. do you think it does not make sense to set a name by the user?
[Screen Shot 2019-04-09 at 2 25 32 PM]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_1648222_55821603-2D40e7a400-2D5ad4-2D11e9-2D8a2d-2D81d64fd09e00.png&d=DwMFaQ&c=96ZbZZcaMF4w0F4jpN6LZg&r=Q1_WK8mWWUtQ5xZX1lcsIPCasN7Y3hsyzvEZltDs4Vs&m=8w34xv0sw36YDB2zASvG4cb-Vtyqdkrs3LSfmkamUpc&s=34VodCsFolMwIbBcF038TmUqOvWY80lIKOldEuN_eFI&e=>

**Comment by joaquin-gimenez** [comment]
@synedra since it always creates a cpcode by default what do you think about renaming --newcpcode to --cpcodename ? I think it's a bit less confusing

**Comment by joaquin-gimenez** [comment]
@synedra want to make sure i prioritize the different scenarios right.
1) on —cpcode and —newcpcode provided at same time, we ignore —cpcode and create a new code with —newcpcode as name
2) on —file with cpcode on it. and --cpcode - we create the property from —cpcode and not cpcode on file
3) on —file with cpcode on it, and —newcode - we create the property from —newcpcode  as name and ignore the existing cpcode on —file 
4) on --clone and  --cpcode - we create the property from —cpcode and not cpcode on file
5) on —clone and —newcpcode - we create the property from —newcpcode as name and ignore the existing cpcode on existing property

**Comment by synedra** [comment]
I like these.  Go ahead and make them work.

Kirsten
