### ISSUE TITLE
Create hostnames with akamai property create

### ISSUE THREAD

**Issue by ghost** [akamai/cli-property#154]
Currently property create does not create new hostnames, but it's important that we add this functionality.

**Comment by synedra** [comment]
Sounds like what we need to do is use the edgehostname endpoint for PAPI.  Let me know if you need more info on that.

**Comment by synedra** [comment]
https://developer.akamai.com/api/core_features/property_manager/v1.html#creatingedgehostnames

**Comment by joaquin-gimenez** [comment]
@khunter if you create with flag hostnames but without edgehostname it had a bug where it did not create a new edgehostname and I fixed that( if(hostname.domainPrefix = configName){  replaced = with ==) . Attatching bug code. So this is good but:
According to the code it looks like it should not assign the hostnames to that property if it is a new edgehostname? so what should it really do in this situation? I'm attatching code.

**Comment by synedra** [comment]
No, it should create the edgehostname and assign host names.

Kirsten

Sent from my iPhone

On Apr 17, 2019, at 8:35 AM, Joaquin Gimenez <notifications@github.com<mailto:notifications@github.com>> wrote:


@khunter<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_khunter&d=DwMFaQ&c=96ZbZZcaMF4w0F4jpN6LZg&r=Q1_WK8mWWUtQ5xZX1lcsIPCasN7Y3hsyzvEZltDs4Vs&m=1auyU-su99oQvc33IXgsFEBmwOpehbL-Ew-fDqH1hAg&s=y_DTd9gTjcJw4b4KbSe9UQvj8C2GXMYAeZIrFK0m-HU&e=> if you create with flag hostnames but without edgehostname it had a bug where it did not create a new edgehostname and I fixed that( if(hostname.domainPrefix = configName){ replaced = with ==) . Attatching bug code. So this is good but:
According to the code it looks like it should not assign the hostnames to that property if it is a new edgehostname? so what should it really do in this situation? I'm attatching code.
