### ISSUE TITLE
P0: Add a sub-command to list products

### ISSUE THREAD

**Issue by javiergarza** [akamai/cli-property#157]
You need to be able to select the products in order to create a new property using the "create" command.

It will be great to implement a new command called "products" that will list all the product available in a contract.

Implement this is rather simple, just get the list of contract IDs on an array (https://developer.akamai.com/api/core_features/property_manager/v1.html#getcontracts) and then run the the call to pull all the products on each contract
https://developer.akamai.com/api/core_features/property_manager/v1.html#getproducts

It will be great if the call would allow passing a contract_ID as optional parameter to filter products on a given contract.

It is fine if we just return the JSON returned by the API call /papi/v1/products

**Comment by joaquin-gimenez** [comment]
![Screen Shot 2019-09-06 at 3 27 33 PM](https://user-images.githubusercontent.com/1648222/64451711-22093000-d0bb-11e9-9ca9-e36d2d90bb54.png)
@javiergarza as you can see when retrieving for all contracts(in this case there's only one), I made it to only return the productID and productName asociated with the contract. if a --contract is passed it will return the response from the endpoint(has a little more info on the product). Is this what you had in mind? let me know of any changes you want to do to it.

**Comment by javiergarza** [comment]
Yes, that’s great! The goal is to have something like the “groups” subcommand but that would display all the contracts and the associated products in each contract.

Thanks!

Javier Garza  |  Senior Developer Evangelist   <https://www.linkedin.com/in/jjgarza/> <https://twitter.com/jjaviergarza>
408-650-0068 | San Francisco, CA
 
T]-[£®& λ1²£ |\|[] §3©я37ŝ |"()я ∂ ©µ2][*[_]$ ^^1(\)Ðoal

**Comment by synedra** [comment]
This looks great, please merge it in.
