### ISSUE TITLE
Need to work with existing hostname

### ISSUE THREAD

**Issue by synedra** [akamai/cli-property#158]
If an edge hostname already exists, it is failing.  Need to pull the ID for the existing edge hostname and use that:

	 {"statusCode":400,"body":"{\n  \"type\" : \"https://problems.luna.akamaiapis.net/papi/v0/edgehostname/not-available\",\n  \"title\" : \"Edge Hostname not available\",\n  \"detail\" : \"The Edge Hostname `example.astronaut.training.edgesuite.net` is not available.\",\n  \"instance\" : \"https://akab-5m47b2yfgkr3thkd-fawku2qvosxppcuq.luna.akamaiapis.net/papi/v1/edgehostnames?contractId=ctr_P-2RQS1FR&groupId=grp_143649#081a5cd6c7bc0bc6\",\n  \"status\" : 400\n}","headers":{"papi-cache-status":"CACHE_MISS","content-language":"en","vary":"Accept-Encoding","content-type":"application/problem+json;charset=UTF-8","x-trace-id":"081a5cd6c7bc0bc6","content-length":"412","date":"Sat, 11 May 2019 13:01:48 GMT","connection":"close"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"akab-5m47b2yfgkr3thkd-fawku2qvosxppcuq.luna.akamaiapis.net","port":443,"hostname":"akab-5m47b2yfgkr3thkd-fawku2qvosxppcuq.luna.akamaiapis.net","hash":null,"search":"?contractId=ctr_P-2RQS1FR&groupId=grp_143649","query":"contractId=ctr_P-2RQS1FR&groupId=grp_143649","pathname":"/papi/v1/edgehostnames","path":"/papi/v1/edgehostnames?contractId=ctr_P-2RQS1FR&groupId=grp_143649","href":"https://akab-5m47b2yfgkr3thkd-fawku2qvosxppcuq.luna.akamaiapis.net/papi/v1/edgehostnames?contractId=ctr_P-2RQS1FR&groupId=grp_143649"},"method":"POST","headers":{"Content-Type":"application/json","User-Agent":"AkamaiCLI/1.1.3 AkamaiCLI-property/1.1.0","Authorization":"EG1-HMAC-SHA256 client_token=akab-ikva4cwwa67fks62-cbmm4orbs4xgvlwr;access_token=akab-yu4tfn36s7wgtjew-5jwn6hqkzw7jsmar;timestamp=20190511T13:01:48+0000;nonce=ea3d328e-f72c-4159-83f4-77b56f345ebe;signature=x4Ofu/5Ic/bRMLY8cOhVqYO6uXbXMFvfEeQw3gi6owU=","content-length":154}}}

**Comment by joaquin-gimenez** [comment]
@synedra can you provide me with the command to reproduce it, thanks

**Comment by synedra** [comment]
Edge Hostname was in a different account
