### ISSUE TITLE
TypeError: Cannot read property 'productId' of undefined

### ISSUE THREAD

**Issue by mguentge** [akamai/cli-property#16]
$ akamaiProperty --group grp_102545 --contract ctr_3-1EOIB4H create template.com
Creating new property template.com
... retrieving list of Group Ids
... retrieving list of Products for this contract
... retrieving list of Products for this contract
ERROR:  {}
TypeError: Cannot read property 'productId' of undefined
    at _getPropertyInfo.then.then.data (/Users/mguentge/tmp/questback/akamaiconfigkit-public/src/website.js:1915:33)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)

The error is caused by line 1915 in website.js
                productId = data.productId;
With setting productID hard corded, it was able to overcome. 
                productId = "prd_Alta";

_getMainProduct() should recognize Alta (id prd_Alta) although it is an old service actually (line 398).
                        } else if (item.productId == "prd_Alta") {
                            productInfo = {
                                productId: "prd_Alta",
                                productName: "Alta",
                                groupId: groupId,
                                contractId: contractId
                            }
                            resolve(productInfo);
                        }

I wasn't able to add this by myself.

**Comment by synedra** [comment]
Added Alta.  Should probably get a list from someone, somewhere, about which products to include
