### ISSUE TITLE
addhosts doesn't actually adds thew new hosts

### ISSUE THREAD

**Issue by vishalchangrani** [akamai/cli-property#162]
I ran the following command to add a new hostname to an existing property. The command succeeds as shown below, a new version of the delivery config is also created but the new hostname is NOT added. The old ones are retained. 

akamai property  --section default  --contract C-XXXX  --group 49XXX modify  mypoc  --addhosts vanityname2.com --new
... searching propertyName for mypoc
... getting info for prp_547783
Creating new version for mypoc
... copy property (mypoc) v9
Command time: 0.087 mins

This is against an Ion Config using ESSL.

**Comment by aalquist** [comment]
you need to run the command again without -new.
