### ISSUE TITLE
P1: Hostname not created on property create

### ISSUE THREAD

**Issue by thestarryknight** [akamai/cli-property#165]
I'm working with a customer who is getting the following error on both `v 1.1.2` and `v 1.1.3`:

`ERROR: Unable to assign hostname. Please try to add the hostname in 30 minutes using the --addhosts flag. 
Unable to assign hostname. Please try to add the hostname in 30 minutes using the --addhosts flag.`

They are running the following command which has worked for them since November:

`akamai property create cloud-usethisapi-qa --clone cloud-template-qa-v2 --hostnames cloud-usethisapi-qa.com --origin usethisapi-qa.mybluemix.net  &>  archive/clone_create.txt`

I did ask them if this could be due to the Edge hostname not existing already and they need to try to create the Edge hostname via postal first, but given it's worked for them since November, that doesn't seem to be the issue here.

**Comment by joaquin-gimenez** [comment]
@thestarryknight hi, i'll be working on the issue, could i have a copy of the file "archive/clone_create.txt" thanks

**Comment by thestarryknight** [comment]
Hi @joaquin-gimenez I am checking with our customer to get the requested text file. 

Here is the current output we got from them:


```
================================
... searching propertyName for zz-cloud-template-qa-v2 

... getting info for prp_505636 

... retrieving clone info 

... retrieving clone rules for cpcode 

Creating property config zz-cloud-usethisapi-qa 

Retrieving zz-cloud-usethisapi-qa v1 

... retrieving property (zz-cloud-usethisapi-qa) v1 

... updating property (zz-cloud-usethisapi-qa) v1 

... retrieving list of hostnames {ctr_C-XXXXXX : grp_XXXXXXX : prp_XXXXXXX} 

Updating property hostnames 

Adding hostname zz-cloud-usethisapi-qa.zz.com 

ERROR: Unable to assign hostname. Please try to add the hostname in 30 minutes using the --addhosts flag. 

Unable to assign hostname. Please try to add the hostname in 30 minutes using the --addhosts flag.
================================```

**Comment by joaquin-gimenez** [comment]
@thestarryknight i thought "clone_create.txt" file was a configuration file, but i pretty sure it's just a file to save the response output to so don't worry about it.
i did notice the property it's trying to clone from does not exist. please let me know if this could be the issue
![Screen Shot 2019-07-19 at 3 18 29 PM](https://user-images.githubusercontent.com/1648222/61556714-d6ca8d80-aa38-11e9-9611-bf5efc7cbec7.png)

**Comment by thestarryknight** [comment]
Thanks @joaquin-gimenez. So the customer mentioned this was working for them since November of last year and no changes were made. Note that in order to keep the customer's anonymity, I removed a few items from the file name. I can e-mail you the full command separately so we don't have the customer's name/config exposed

**Comment by joaquin-gimenez** [comment]
@thestarryknight i saw the original command from the email, thanks

**Comment by thestarryknight** [comment]
Hi @joaquin-gimenez Any updates on this? Thank you

**Comment by joaquin-gimenez** [comment]
Hi @thestarryknight, it looked like an issue on the PAPI endpoint and not cli-property so @synedra was going to forward it to who is in charge

**Comment by thestarryknight** [comment]
Hi @synedra Any chance this is associated with anything on the new ACC? The customer only started noticing it recently and it happens on a few different machines, i.e. customer's local Mac, Jenkins instance

**Comment by thestarryknight** [comment]
Hi @synedra We're currently on a call with the customer and they would like some kind of update, in particular with these errors. Are you aware of any issues that perhaps the new portal could be causing this? The customer noticed this latest error following the latest portal release

**Comment by thestarryknight** [comment]
We can close this issue, ended up being a portal permissions issue. Sorry for not updating earlier.
