### ISSUE TITLE
update should be able to take comments

### ISSUE THREAD

**Issue by akamai-jmar** [akamai/cli-property#174]
Copy of #90. The fix (#123) is no longer available in latest CLI on master branch.

"update should also be able to take a --comments argument so that version notes can be added. Otherwise you have to run modify --comments after calling update"

**Comment by joaquin-gimenez** [comment]
@akamai-jmar The command accepts --notes to leave a comment and it looks to be working fine, if you still have the issue let us know. you can check the available options with "akamai property update --help"
cheers

**Comment by akamai-jmar** [comment]
Hi @joaquin-gimenez, thanks, I see it was fixed in c2fa479905735b25869dd28d8149981a4188ed1f

Closing this issue.
