### ISSUE TITLE
search / "Cannot read property 'account-key' of undefined

### ISSUE THREAD

**Issue by ynohat** [akamai/cli-property#189]
**Repro**

```
$ akamai property search --section abc xyz
(usage info)

ERROR: 
        Cannot read property 'account-key' of undefined
```

**Version**

```
$ akamai property --version
1.1.5
```

**Comment by javiergarza** [comment]
@ynohat I can repro too. I will try to get one of our Developers to take a look

**Comment by joaquin-gimenez** [comment]
@ynohat would "abc xyz" be the name of the section? otherwise what is "xyz"?

**Comment by ynohat** [comment]
Abc is the section, xyz is the prop name to search for

**Comment by ynohat** [comment]
> @ynohat I can repro too. I will try to get one of our Developers to take a look

Thanks @javiergarza
