### ISSUE TITLE
Akamai cli property activation returns intermittent 'statusCode' of undefined

### ISSUE THREAD

**Issue by massifazio** [akamai/cli-property#192]
Akamai cli activation command returns an undefined response code
akamai property activate returns -->
Cannot read property 'statusCode' of undefined

we noticed the issue when running from my laptop macOs and from a Jenkins job running red-hat . 

The command :
**akamai property activate api-cdt.maersk.com --network PROD --notes AOP-3520 --email jamal.sia@maersk.com**

the error is :
/Users/vanilla/.akamai-cli/src/cli-property/src/website.js:1077
if (response.statusCode === 200 && /application\/json/.test(response.headers['content-type'])) {
^

TypeError: Cannot read property 'statusCode' of undefined
at /Users/vanilla/.akamai-cli/src/cli-property/src/website.js:1077:38
at EdgeGrid.<anonymous> (/Users/vanilla/.akamai-cli/src/cli-property/node_modules/edgegrid/src/api.js:81:7)
at self.callback (/Users/vanilla/.akamai-cli/src/cli-property/node_modules/request/request.js:185:22)
at Request.emit (events.js:203:13)
at Request.onRequestError (/Users/vanilla/.akamai-cli/src/cli-property/node_modules/request/request.js:881:8)
at ClientRequest.emit (events.js:203:13)
at TLSSocket.socketErrorListener (_http_client.js:399:9)
at TLSSocket.emit (events.js:203:13)
at emitErrorNT (internal/streams/destroy.js:91:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)

this only happens when deploying to the production network.
this behavior seems to happen when the cli keeps polling the akamai property manager api for status. In some cases, the response is not captured and an undefined value is returned in the response. this triggers a failure of the activation.
So far , we have not noticed that error from the LUNA portal activation.

![image](https://user-images.githubusercontent.com/53767957/72813166-33ff0000-3c63-11ea-8149-3dc3d3387769.png)

![image](https://user-images.githubusercontent.com/53767957/72813207-41b48580-3c63-11ea-8088-852a1d5e9de3.png)

**Comment by jamalsia** [comment]
i was wondering if we could enable a debug mode in the cli. this could help us dig deeper in the response captured. 
the actual behavior described above is intermittent.

**Comment by Senopratomo** [comment]
_TypeError: Cannot read property 'statusCode' of undefined_ means the API call (HTTP request) which CLI made under the hood doesn't receive any valid HTTP response (thus 'statusCode' of undefined on response.statusCode).
This usually cause by network issue, eg connection between client to remote server drop prematurely, etc
If it happen intermittently, I'd suggest doing some sort of retry in the workflow
