### ISSUE TITLE
Unable to activate specific version

### ISSUE THREAD

**Issue by ghost** [akamai/cli-property#22]
Need to be able to activate from prod, staging, latest, or any specific version

**Comment by jaescalo** [comment]
I am using the following syntax:
$ akamai property activate jaescalo-testing --section akamps --network STAG --propver v36

Is this ok, and/or is this still an issue?

**Comment by jasony87** [comment]
I am unable to activate specific versions
akamai property --section property --propver 686 --network staging --propver 686 activate  <property name>

I've tried moving the flags around but it'll only ever try to activate the latest version.

**Comment by synedra** [comment]
Hi Jason!

I just committed a new version which should work correctly with the selected version.  I changed the flag name and didn't catch the resulting issue.

I'm checking on the issue with the restricted number of behaviors/rules and will get back to you as soon as I get an answer.

Thanks :-)

Kirsten



On November 13, 2017 at 11:44:18 AM, jasony87 (notifications@github.com<mailto:notifications@github.com>) wrote:

I am unable to activate specific versions
akamai property --section property --propver 686 --network staging --propver 686 activate

I've tried moving the flags around but it'll only ever try to activate the latest version.

**Comment by dhambali** [comment]
Related to this, I'm unable to retrieve by --propver.

$ akamai update
Attempting to update "auth" command...... [OK]
command "auth" already up-to-date
Attempting to update "netstorage" command...... [OK]
command "netstorage" already up-to-date
Attempting to update "property" command...... [OK]
command "property" already up-to-date
Attempting to update "purge" command...... [OK]
command "purge" already up-to-date

$ akamai property --propver v105 retrieve <property>
Unable to parse version string, using latest
... searching propertyName for <property>
... getting info for prp_******
Retrieving <property> v106
... retrieving property (<property>) v106
