### ISSUE TITLE
Unable to link cloned to config to Edge Hostname

### ISSUE THREAD

**Issue by roryhewitt** [akamai/cli-property#25]
When cloning an existing config to a new config, I specify an Edge Hostname (which exists, but it not explicitly linked to any properties), and I get the following error:

`./akamaiProperty create july21scm --clone secure-m.example.com_template --hostnames secure-m.example-int021.c4d.devops.example.com --origin origin-secure-m.example-int018.c4d.devops.example.com --edgehostname example4.edgekey.net
`
```
ERROR:  {
  "type" : "https://problems.luna.akamaiapis.net/papi/v0/property-version-hostname/bad-cnameto",
  "title" : "Bad `cnameTo`",
  "status" : 400,
  "detail" : "The System could not find cnameTo value `example4.edgekey.net`.",
  "instance" : "https://akab-3eatgwr3lu3fh6dk-hddwfvupvajsqhp4.luna.akamaiapis.net/papi/v0/properties/prp_391196/versions/1/hostnames/?contractId=ctr_1-1U72M7&groupId=grp_101490#69d956cf-1e55-406e-890f-e0dad98cee8d"
}
```
The example4.edgekey.net Edge Hostname does exist, and it's linked to this contract - don't know if it's linked to this group.

**Comment by synedra** [comment]
This is a PAPI error (hence the 400), so it may be that those credentials can't see that hostname?

**Comment by synedra** [comment]
Closing as it's likely a permission issue.
