### ISSUE TITLE
Add support for Rich Media Accel and update api urls

### ISSUE THREAD

**Issue by orderedchaosdev** [akamai/cli-property#27]
Current version errors since Rich Media Accel is not defined in the list of products.
Also the papi api urls still point to v0 when the api docs say to use v1 and that v1 should be backwards compatible with all v0.

I have made a pull request that has these changes.

[Updated paths to use v1 papi instead of v0 and added Rich Media Accel](https://github.com/akamai/cli-property/pull/26)

**Comment by synedra** [comment]
I've made the changes and committed them.

Thanks!
