### ISSUE TITLE
Activation does not return any result

### ISSUE THREAD

**Issue by VasudevanGIT** [akamai/cli-property#28]
For eg: ./akamaiProperty activate ##prop## name --network staging

Returns output like

Waiting for 30 sec a few times and then completes successfully..

It would be nice to see some status like 

"Activation Completed" etc..

same as ./akamaiProperty create which returns Creation Complete when it finishes..

**Comment by plermant** [comment]
In addition to "Activation Completed" it could be useful to add the activation time it took.

**Comment by synedra** [comment]
Functionality added.
