### ISSUE TITLE
Retrieve fails

### ISSUE THREAD

**Issue by akshayranganath** [akamai/cli-property#29]
Since the morning of August 4th PST, the command to retrieve rules has been failing. I verified if it is an issue by using the raw PAPI call and that succeeded.  Here's the error that I get:

```bash
$ ./akamai.exe property retrieve devopstest.gcs.com
Retrieving devopstest.gcs.com
... retrieved rules formats: 1214.344ms
Initializing property cache
Init PropertyManager cache (hostnames and property list)
... retrieving list of Group Ids
... retrieving properties from 10 groups
... retrieving Hosts from 163 properties
... Error from server for prp_11111
... Error from server for prp_2222
... and so on.
```

**Comment by synedra** [comment]
Akshay,

Is this still broken?  Let me know - usually it's a PAPI issue but as you said you tested it.  I haven't seen any changes myself.

Thanks,
Kirsten

**Comment by akshayranganath** [comment]
This issue is no longer occurring. Thanks for checking.
