### ISSUE TITLE
Create property command ignores group id and fails

### ISSUE THREAD

**Issue by VasudevanGIT** [akamai/cli-property#31]
$ ./akamaiProperty create dummywwwtest --file www_template.xml --hostnames *** --origin *** --edgehostname *** --group 101490
Creating new property dummywwwtest

  Usage: akamaiProperty [options] [command]

  Options:

    -h, --help  output usage information

  Commands:

    help [command]
    activate [options] <property>
    create [options] <property>
    deactivate [options] <property>
    formats [options]
    delete [options] <property>
    retrieve [options] <property>
    update [options] <property>
    modify [options] <property>

**Comment by plermant** [comment]
try with 
--group grp_101490
--contract ctr_1-1U72M7

**Comment by VasudevanGIT** [comment]
Works fine with those parameters.. Thanks !!

**Comment by synedra** [comment]
This should be fixed now, contract is auto-determined by group
