### ISSUE TITLE
Delete config fails if the config has not been activated

### ISSUE THREAD

**Issue by akshayranganath** [akamai/cli-property#35]
When trying to delete a configuration, it looks like the CLI issues a call to de-activate the configuration on staging and prod. However, it looks like it does not check if the configuration is even active on either of the networks.

Due to this, we are seeing an error where the delete never really works. Here's the trace of the request.

**Creating a new configuration**
```bash
$ ./akamai property create testdemo.ephemeral-config.com --hostnames test.test.com --origin origin-test.test.com
Creating new property testdemo.ephemeral-config.com
... retrieving list of Group Ids
... retrieving list of Products for this contract
... retrieving list of Products for this contract
Creating property config testdemo.ephemeral-config.com
... creating: 6584.003ms
... retrieved rules formats: 563.067ms
Initializing property cache
Init PropertyManager cache (hostnames and property list)
... retrieving list of Group Ids
... retrieving properties from 10 groups
... retrieving Hosts from 178 properties
Init PropertyManager cache: 80499.980ms
Creating new CPCode for property
... creating new CPCode: 252.947ms
```

**Deleting the configuration**
```bash
$ ./akamai property delete testdemo.ephemeral-config.com
Deleting testdemo.ephemeral-config.com
... retrieved rules formats: 1512.737ms
... searching propertyName for testdemo.ephemeral-config.com
... searching hostname for testdemo.ephemeral-config.com
... searching edgeHostname for testdemo.ephemeral-config.com
Cannot locate property using search
Initializing property cache
Init PropertyManager cache (hostnames and property list)
... retrieving list of Group Ids
... retrieving properties from 10 groups
... retrieving Hosts from 178 properties
Init PropertyManager cache: 4495.350ms
Deactivating testdemo.ephemeral-config.com to STAGING
... deactivating property (testdemo.ephemeral-config.com) v1 on STAGING
ERROR:  "{\n  \"type\" : \"https://problems.luna.akamaiapis.net/papi/v0/toolkit/property_version_not_active_in_staging\",\n  \"instance\" : \"https://akab-eyt7c2nuge444oiq-dhyxfhoxgujxsoji.luna.akamaiapis.net/papi/v1/properties/prp_399543/activations?contractId=ctr_C-1ED34DY&groupId=grp_63802#16f7d62d-fd7e-475d-84fc-3f47b6ac37a6\",\n  \"params\" : [ \"testdemo.ephemeral-config.com\" ]\n}"
```

The use case we're trying to cover is the following:
The only way for a customer to easily validate the metadata is to push it as a configuration. If they're building an ephemeral config, this may be the only way. If they see any errors and want to delete the config, it will block their work-flow.

**Comment by dmcallis1** [comment]
Additional observation: the CLI will not permit removal of properties even that have not been activated on staging AND production. 

`akamai property delete devopstest-qa-11.gcs.com
Deleting devopstest-qa-11.gcs.com
... retrieved rules formats: 739.998ms
... searching propertyName for devopstest-qa-11.gcs.com
... getting info for prp_399540
Deactivating devopstest-qa-11.gcs.com to STAGING
... deactivating property (devopstest-qa-11.gcs.com) v1 on STAGING
...
Deactivating devopstest-qa-11.gcs.com to PRODUCTION
... deactivating property (devopstest-qa-11.gcs.com) v1 on PRODUCTION
ERROR:  "{\n  \"type\" : \"https://problems.luna.akamaiapis.net/papi/v0/toolkit/property_version_not_active_in_production\",\n  \"instance\" : \"https://akab-uulemrmaiat7xtl6-ipfwzox4cdhka7ux.luna.akamaiapis.net/papi/v1/properties/prp_399540/activations?contractId=ctr_C-1ED34DY&groupId=grp_63802#66cdd6c2-98c1-43c7-9353-7b3b91b5edd9\",\n  \"params\" : [ \"devopstest-qa-11.gcs.com\" ]\n}"`

For the purposes of quick validation within lower stage ephemeral environments, we do not necessarily need to activate our configuration in both PROD and Staging networks.

**Comment by synedra** [comment]
Are you using the most recent version? This should no longer be the case.  However, I'll take a look and see what's up with it.

Kirsten

**Comment by dmcallis1** [comment]
@synedra - we're using the 'akamai update' facility to keep the property package up to date.. assuming that's the prescribed method? We actually have a cronjob to check for updates hourly :)

**Comment by synedra** [comment]
Ok, should be working then.  Let me fuss with it some and see what's up.

Kirsten

**Comment by synedra** [comment]
Weirdly I don't see this behavior.  When I create a fresh property and then tear it down (without activating or deactivating) it just goes through the process completely.

I did make a change just now that might potentially fix the issue.

The other question I have is what version of node you have, in case the match works differently.

I did 'akamai update' to make sure I'm using the same version

MacBook-Pro-5:cli-property khunter$ akamai property delete test.deactivation.com
Deleting test.deactivation.com
... retrieved rules formats: 734.200ms
... searching propertyName for test.deactivation.com
... searching hostname for test.deactivation.com
... searching edgeHostname for test.deactivation.com
Cannot locate property using search
Initializing property cache
Init PropertyManager cache (hostnames and property list)
... retrieving list of Group Ids
... retrieving properties from 22 groups
... no permissions, ignoring  {ctr_F-FABEOR : grp_101230}
... retrieving Hosts from 286 properties
Init PropertyManager cache: 2470.016ms
... no permissions, ignoring  {ctr_F-FABEOR : grp_101230}
Deactivating test.deactivation.com to STAGING
... deactivating property (test.deactivation.com) v1 on STAGING
Version not active on STAGING
Deactivating test.deactivation.com to PRODUCTION
... deactivating property (test.deactivation.com) v1 on PRODUCTION
Version not active on PRODUCTION
Deleting test.deactivation.com
... deleting property: 314.947ms
Delete Complete
Delete: 0.21443333333333334 mins

**Comment by dmcallis1** [comment]
@synedra seems to be working now!

```
jenkins@ip-10-0-1-60:~$ akamai property delete devopstest-qa-10.gcs.com
Deleting devopstest-qa-10.gcs.com
... retrieved rules formats: 679.216ms
... searching propertyName for devopstest-qa-10.gcs.com
... searching hostname for devopstest-qa-10.gcs.com
... searching edgeHostname for devopstest-qa-10.gcs.com
Cannot locate property using search
Initializing property cache
Init PropertyManager cache (hostnames and property list)
... retrieving list of Group Ids
... retrieving properties from 10 groups
... retrieving Hosts from 180 properties
Init PropertyManager cache: 1613.596ms
Deactivating devopstest-qa-10.gcs.com to STAGING
... deactivating property (devopstest-qa-10.gcs.com) v1 on STAGING
Version not active on STAGING
Deactivating devopstest-qa-10.gcs.com to PRODUCTION
... deactivating property (devopstest-qa-10.gcs.com) v1 on PRODUCTION
Version not active on PRODUCTION
Deleting devopstest-qa-10.gcs.com
... deleting property: 466.261ms
Delete Complete
Delete: 0.22005 mins
```
