### ISSUE TITLE
Why does create limit the usage only to certain products (see private function _getMainProduct) at website.js?

### ISSUE THREAD

**Issue by cpinotossi** [akamai/cli-property#38]
Is there a good reason to limit create to only certain Akamai Products?
If yes, could we extend it to also support 

                "productId": "prd_Download_Delivery",
                "productName": "Download_Delivery"

and

                "productId": "prd_IoT",
                "productName": "IoT"

**Comment by synedra** [comment]
This has been updated.  We need the main product for the group in order to correctly create a property with the right spec.
