### ISSUE TITLE
Modify property throws an error when trying to add a new hostname

### ISSUE THREAD

**Issue by plsalvado** [akamai/cli-property#39]
I'm trying to add a new hostname to an existing property by using the command: 
`akamai property --section default modify akamai-amd-test.salvado.me --addhosts akamai-test-amd2.pedro.media`

When the CLI is trying to add the hostname it returns the following error:
```
Updating property hostnames
Adding hostname akamai-test-amd2.pedro.media
Adding hostname akamai-test-amd1.pedro.media
... updating hostname: 4309.482ms
(node:57080) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): #<IncomingMessage>
(node:57080) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Note: akamai-test-amd1.pedro.media is an existing hostname in an already deployed property

**Comment by synedra** [comment]
This has been resolved.
