### ISSUE TITLE
Unable to Modify the Property if existing property did not have hostnames

### ISSUE THREAD

**Issue by ctuppad** [akamai/cli-property#49]
HI,

The following scenarios does not seem to be working.
Step 1: Create a property using CLI without hostname.
Step 2: Modify the property with hostname using CLI. This throws an error and does not add the hostname. ( When checked the code, it seems while adding hostname it first tries to retrieve existing set of hostnames and then add into the list. If, there are no existing hostnames: code does not fetch existing hostname: null and hence throws error). If the existing property has a hostname, while updating new hostname via CLI - it works.
PFA the use case.

<img width="1066" alt="33715739-9d70499c-db79-11e7-965d-32d9ee125012" src="https://user-images.githubusercontent.com/34309060/33729670-59118088-dba4-11e7-9896-b5389a27f399.png">

**Comment by synedra** [comment]
Should be easy to fix, I'll get on it today.

**Comment by synedra** [comment]
This works correctly now
