### ISSUE TITLE
Add ability to set cpcode in Modify call

### ISSUE THREAD

**Issue by plermant** [akamai/cli-property#50]
Since cpcode cannot be set by a variable, it is critical to have the ability to set it thru the CLI command itself when a config is modified.
Ask is to add the ability to change the Default rule cpcode with a "--cpcode" parameter in the Modify call.

**Comment by synedra** [comment]
Resolved :-)

**Comment by dmcallis1** [comment]
@synedra - I'm also interested in this CLI feature in support of a project for another customer... while the new flag does modify the CP code, I'm experiencing some strange behavior. Within my default rule, all behaviors are being duplicated:

  "errors": [
    {
      "type": "https://problems.luna.akamaiapis.net/papi/v0/validation/too_many_instances",
      "errorLocation": "#/rules/behaviors/5",
      "detail": "There are 2 instances of the behavior, `Enhanced Akamai Protocol`, in this property. You can only use this behavior 1 time(s)."
    },

**Comment by synedra** [comment]
Can you give me a set of commands to reproduce?  I’m not seeing it here but I’m proably just missing something.

Thanks,
Kirsten

**Comment by dmcallis1** [comment]
Sorry about that! The command completes successfully, and does change the CP code in the default rule.. however all behaviors are duplicated for some reason.

Here's the command

atl-mp43o:~ dmcallis$ akamai property modify cert-2.abercrombie.com_pm --cpcode 463535
... retrieved rules formats: 871.395ms
... searching propertyName for cert-2.abercrombie.com_pm
... getting info for prp_428391
... retrieving property (cert-2.abercrombie.com_pm) v9
... retrieving: 2339.810ms
... updating property (cert-2.abercrombie.com_pm) v9
... updating: 30469.809ms
Command time: 0.59 mins

![image](https://user-images.githubusercontent.com/30732612/34550311-d72c123c-f0dd-11e7-8956-dcb9eed00d72.png)

**Comment by synedra** [comment]
This should be fixed now, give it a go and let me know if there’s still an issue.

Thanks,
Kirsten

**Comment by dmcallis1** [comment]
@synedra - confirmed, works following latest update!

As always, thanks so much!
