### ISSUE TITLE
WAF

### ISSUE THREAD

**Issue by PatrickWalters** [akamai/cli-property#53]
A WAF deny rule IPBLOCK-BURST4-54013 gets triggered when attempting to run cli on windows machine:

C:\Users\pwalters>akamai-0.4.2-windows386.exe property create mynewproperty123 --clone myoldproperty123 --section general

...

body: '{\n  "type": "https://problems.luna.akamaiapis.net/-/pep-authn/request-
error",\n  "title": "Bad request",\n  "status": 400,\n  "detail": "WAF deny rule
 IPBLOCK-BURST4-54013",\n  "instance": "https://akab-xxxxxxxxxxxxxxxx-yyyyyyyyyyyyyyyy.luna.akamaiapis.net/papi/v1/properties?contractId=ctr_C-XXXXXXX&groupId=g
rp_123456",\n  "method": "GET",\n  "serverIp": "104.125.30.168",\n  "clientIp":
"88.221.208.10",\n  "requestId": "366e36b9",\n  "requestTime": "2018-01-10T06:45
:48Z"\n}\n' }
[object Object]

**Comment by PatrickWalters** [comment]
This was a result of installing property without node.js and the binary was obtained. After node js was installed, this was successful. Is there anyway to put in a stop-gap to avoid retrying at the rate which triggers WAF?

**Comment by synedra** [comment]
The most recent version of the CLI no longer crawls the account when a mistyped property name is used.  The binary should work now as well (assuming you have the latest one).

Thanks,
Kirsten

**Comment by synedra** [comment]
This should be fixed now.  Please feel free to re-open if you're still seeing problems.
