### ISSUE TITLE
Issue with --addhosts

### ISSUE THREAD

**Issue by javiergarza** [akamai/cli-property#54]
Found a couple of issues with addhosts. The name indicates it should add new host(s) to the configuration but right now it just replaces any existing host(s) with the one given as a parameter.

Issue 1) Property has 1 hostname called jgarza.sandbox.akamaideveloper.com. The command below replaces that hostname with jgarza-stg.sandbox.akamaideveloper.com

akamai property modify jgarza.sandbox.akamaideveloper.com --addhosts jgarza-stg.sandbox.akamaideveloper.com

Issue 2) The property has 2 hostnames called jgarza.sandbox.akamaideveloper.com and jgarza2.sandbox.akamaideveloper.com. The command below replaces those 2 hostnames with 1 hostname called jgarza3.sandbox.akamaideveloper.com

akamai property modify jgarza.sandbox.akamaideveloper.com --addhosts jgarza3.sandbox.akamaideveloper.com

**Comment by synedra** [comment]
Fixed in the latest release (including binaries)
