### ISSUE TITLE
Unable to move a property from one folder to another.

### ISSUE THREAD

**Issue by dhambali** [akamai/cli-property#56]
DevOps World Tour [~] >>   akamai property modify testing111.foo.com --move Devops
Moving testing111.foo.com to Devops
... retrieved rules formats: 6274.915ms
... searching propertyName for testing111.foo.com
... getting info for prp_1111111
Gathering asset ID for property
... requesting: 99.514ms
ERROR:  Unable to access user administration.  Please ensure your credentials allow user admin access.
Unable to access user administration.  Please ensure your credentials allow user admin access.

Am I missing a section in .edgerc beyond [papi], [ccu], [alerts], and [default]?

**Comment by synedra** [comment]
It's not a section, it's a set of permissions.  But if you're using the DevOps world tour credentials you won't be able to move a property.  Those credentials do not have access to other groups so moving a property isn't possible.

From the README file for cli-property:

  *   When working through this process you need to give grants for the property manager API and the User Admin API (if you will want to move properties). The section in your configuration file should be called 'papi'.

Which is to say, you must give access to Property Manager as well as User Admin within the same set of credentials, named "papi".

But as I said, it won't work for the DevOps world tour credentials.  That user does not have access to any other groups.

Kirsten



On January 30, 2018 at 1:31:31 PM, dhambali (notifications@github.com<mailto:notifications@github.com>) wrote:

DevOps World Tour [~] >> akamai property modify testing111.foo.com --move Devops
Moving testing111.foo.com to Devops
... retrieved rules formats: 6274.915ms
... searching propertyName for testing111.foo.com
... getting info for prp_1111111
Gathering asset ID for property
... requesting: 99.514ms
ERROR: Unable to access user administration. Please ensure your credentials allow user admin access.
Unable to access user administration. Please ensure your credentials allow user admin access.

Am I missing a section in .edgerc beyond [papi], [ccu], [alerts], and [default]?

**Comment by dhambali** [comment]
I see where I went wrong.  I assumed I was missing a section in .edgerc, but it was really an authorization in "Manage APIs" under Luna.

Oddly enough, to perform the folder move, I had to enable the deprecated API.

![image](https://user-images.githubusercontent.com/1854558/35594868-8759fca0-05c9-11e8-896e-cc1c6af65c57.png)
