### ISSUE TITLE
Will there be an option to clone a property and strip all hostnames from the clone?

### ISSUE THREAD

**Issue by dhambali** [akamai/cli-property#57]
Will there be an option to clone a property and strip all hostnames from the clone?

**Comment by synedra** [comment]
Please open a separate issue for this, and I'll get it in soon.

Kirsten



On January 30, 2018 at 4:31:56 PM, dhambali (notifications@github.com<mailto:notifications@github.com>) wrote:

Will there be an option to clone a property and strip all hostnames from the clone?

**Comment by synedra** [comment]
Never mind, my mail got confused.  This issue is fine, and I'll reply when I get it done,
