### ISSUE TITLE
Output for "groups" command is not JSON formatted

### ISSUE THREAD

**Issue by akshayranganath** [akamai/cli-property#59]
When trying to retrieve group ID information, the command output is not a well-formatted JSON. This prevents it from being useful for any JSON parsing at a later point.

**Command with issues**
```bash
akamai property groups
```

**Sample output**
```bash
[
{ groupName: 'Dev',
    groupId: 'grp_123456',
    parentGroupId: 'grp_456789',
    contractIds: [ 'ctr_1-12345', 'ctr_C-12345' ] }
]
```

Please could you get the output to be in well-formed JSON format.

**Comment by synedra** [comment]
Fixed, will be in the binaries shortly.  akamai update will get the right version.
