### ISSUE TITLE
Flag to hide the info messages

### ISSUE THREAD

**Issue by akshayranganath** [akamai/cli-property#61]
Currently, the CLI has an option to enable debug mode output using the ```--debug``` flag. It prints info level messages by default.

The info messages are good when users are using the CLI as a stand-along tool. However, if a user wants to chain the command and run the output using ```jq``` , it breaks. This is because the info messages are considered invalid JSON and breaks the parsing.

Would it be possible to provide either a flag or a setting in the ```.edgerc``` file that maintains the verbosity level. By default, it could be set to ```info``` but, it could be changed to ```error``` or ```critical``` as needed. This way, we can chain the commands after CLI to run some tasks like extracting group information or pulling down a rule set.

**Comment by synedra** [comment]
I've switched the info messages to STDERR, which should solve the issue.  This is the new standard for CLI's apparently :-)
