### ISSUE TITLE
akamai property retrieve by version does not work

### ISSUE THREAD

**Issue by akshayranganath** [akamai/cli-property#62]
`akamai property retrieve` has an option to pull down a property configuration by version using the `--propver` option.

However, there are 2 issues with this:
* In the documentation `--propver` shows it to be a `boolean` variable. However, this should be a numeric value.
* Even when a user passes the variable value, the value is rejected. eg: Here is an output message.

```bash
$ akamai property retrieve devopstest-gold.gcs.com --propver 2
Unable to parse version string, using latest
```

This is a critical bug as it prevents users from pulling specific version of the configuration file.

**Comment by synedra** [comment]
This is fixed.  Thanks :-)
