### ISSUE TITLE
read property name from environment variable

### ISSUE THREAD

**Issue by hakamadare** [akamai/cli-property#65]
Entering the property name in each command is a bit onerous; it would be nice to be able to use a workflow like the following:

```sh
$ export AKAMAI_PROPERTY_NAME=foo.example.com
$ akamai property activate --network staging
... retrieved rules formats: 812.964ms
...
```

This would also facilitate managing multiple properties from within a directory hierarchy stored in SCM, perhaps using a tool like [direnv](https://github.com/direnv/direnv).

**Comment by synedra** [comment]
I'll get this in there.  In the meantime you can at least set env variables for authentication (of you don't want to use an edgerc file).  AKAMAI_PAPI_CLIENT_TOKEN, etc.

Poorly documented as of now, but it works in the CLI for PAPI and some other places too.  If it doesn't work somewhere, ping us.

**Comment by synedra** [comment]
Please use env var names consistent with the other papi ones, so:
AKAMAI_PAPI_PROPERTY
