### ISSUE TITLE
Activation polling

### ISSUE THREAD

**Issue by vreddhi** [akamai/cli-property#70]
Can we add an option to activate, which will allow skipping the poll functionality?

This is much useful in CI/CD integration where in customer just needs to activate configuration and move on to next task. Waiting for ~5/10 minutes is not ideal.

Looks like _pollActivation function is always called.

**Comment by synedra** [comment]
I'll look into this for sure!

**Comment by ericdebeij** [comment]
Hi,
Any news on this? I see the activate method now has a wait parameter, but that parameter is never set and it defaults to true.
