### ISSUE TITLE
Property config validation command

### ISSUE THREAD

**Issue by dhambali** [akamai/cli-property#72]
Is there a command (or should there be a command) to check that a config is valid and can be activated without actually activating the config?

Something like:

akamai property validate --ignorewarnings
-or- 
akamai property activate --validate  --ignorewarnings

It would be nice if we could check, but not attempt to activate.  Also, an option to bomb/not bomb if there were warnings.

**Comment by lukaszczerpak** [comment]
You can use `retrieve` command which prints out all errors and warnings.

**Comment by joaquin-gimenez** [comment]
@synedra should we close this issue since we have the retrieve command for it?

**Comment by lukaszczerpak** [comment]
I think so @joaquin-gimenez

**Comment by joaquin-gimenez** [comment]
we are closing this issue since the retrieve command does what is requested.
