### ISSUE TITLE
Unable to update the Property if existing property did not have hostnames

### ISSUE THREAD

**Issue by dshafik** [akamai/cli-property#73]
Via @ctuppad at akamai/cli#29:

HI,

The following scenarios does not seem to be working.
Step 1: Create a property using CLI without hostname.
Step 2: Modify the property with hostname using CLI. This throws an error and does not add the hostname. ( When checked the code, it seems while adding hostname it first tries to retrieve existing set of hostnames and then add into the list. If, there are no existing hostnames: code does not fetch existing hostname: null and hence throws error). If the existing property has a hostname, while updating new hostname via CLI - it works.
PFA the use case.

<img width="1066" alt="33715739-9d70499c-db79-11e7-965d-32d9ee125012" src="https://user-images.githubusercontent.com/58074/37815528-8a00ae6a-2eb2-11e8-86b4-57e9b5820abb.png">

**Comment by amrraj** [comment]
The above scenario is not working. I tried to modify the config after adding a hostname, still same issue. As per the question posted in Aloha, KSD is common to all who are facing this issue. I tried in another customer account where KSD and ION are in separate contract, it works.

**Comment by joaquin-gimenez** [comment]
@dshafik I'm not able to reproduce the issue. If I try to modify without an edgehostname i get another error(no edgename found for property). You can follow the scenario i followed in attachment and let me know if Im missing something in the scenario.
![screen shot 2018-12-18 at 1 10 49 pm](https://user-images.githubusercontent.com/1648222/50166989-e0cfb680-02c6-11e9-95e2-d4c157e0648e.png)
