### ISSUE TITLE
List Properties in Group

### ISSUE THREAD

**Issue by roymartinezblanco** [akamai/cli-property#81]
Hi,

It seems that there is no way to list all configurations in a group. 

It would be useful to get this list for one to iterate thru the list.

**Comment by joaquin-gimenez** [comment]
@roymartinezblanco @synedra what are the configurations being?
maybe you can give me a reference using [papi endpoints](https://developer.akamai.com/api/core_features/property_manager/v1.html) if there is an enpoint retrieveing those configs. thanks

**Comment by synedra** [comment]
They're looking for a list of properties.  i believe the only current way to do it is to do a call to "groups" and pull the properties from there.

**Comment by synedra** [comment]
This needs to be redone - the command line interface will handle "required: true" so you don't need to add all the logic inside of website.js.

**Comment by joaquin-gimenez** [comment]
@synedra please check now, the build failed but because I'm doing the PR from a fork

**Comment by synedra** [comment]
This looks good now, thanks.
