### ISSUE TITLE
"modify" command could be improved to be more intuitive

### ISSUE THREAD

**Issue by akshayranganath** [akamai/cli-property#83]
Currently, the _update_ command works if the configuration is not already activated. If a user tries to run the _update_ on a activated config, they get an error message with this kind of an error message.

```javascript
ERROR:  {
  "type" : "https://problems.luna.akamaiapis.net/papi/v0/property-version/already-activated",
  "title" : "Property version already activated",
  "status" : 403,
```

To work around this issue, users currently need to do the following:

- Run the `akamai property retrieve --file` command to get back the existing JSON
- Run the `akamai property update` command to create a new version with the same code as existing version
- Finally run the `akamai property modify` command to insert the necessary change.

Instead of the user performing these steps, I feel we could offer an option / flag that indicates "create new version and update". This way, users don't have to go through the multi-step process or cause a break in the pipeline.

**Comment by joaquin-gimenez** [comment]
hi @akshayranganath ,
Can you give me more information on the scenario. what flags are you running on the command?
is it happening regardless of if it's active on staging/prod?
I've tried running update from file and from property/propver and am not getting that error
cheers

**Comment by synedra** [comment]
Akshay,

There's now a --new flag which allows you to indicate that you want a new version created.  Does that meet the goals?

**Comment by joaquin-gimenez** [comment]
As discussed with @akshayranganath the --new flag resolves the request so we agreed to close it.
