### ISSUE TITLE
update should be able to take comments

### ISSUE THREAD

**Issue by aetsai** [akamai/cli-property#90]
update should also be able to take a --comments argument so that version notes can be added. Otherwise you have to run modify --comments after calling update

**Comment by joaquin-gimenez** [comment]
@aetsai @synedra @dshafik Should you be able to add a note/comment only if
the update from srcprop/file was successful? or can a note be added independent of if a srcprop/file was provided

**Comment by akamai-jmar** [comment]
This option no longer shows up in the latest version of the CLI, can it be re-committed?
