### ISSUE TITLE
activate and/or update command to return the version number it used

### ISSUE THREAD

**Issue by aetsai** [akamai/cli-property#93]
When plugged into a build pipeline such as jenkins, it would be nice if activate and/or update returned the version number that was activated or updated so we don't have to make parse the output or create a custom script/call to find out what it was to then trigger out what to do next

**Comment by gfirem** [comment]
Hi @aetsai, the output of this command is a json. If you plan to use with jenking take a look at the next library, it will help you. 
https://stedolan.github.io/jq/ 
In the case the output is not only a json, you can add this `2>/dev/null` at the end of the command to discard the stderr outputs and show only the json object comming form the stdout.
The following is an example of the result command:
`jq '.propertyVersion' | akamaiProperty update joaquin45.example.com --file tets.json 2>/dev/null`

**Comment by joaquin-gimenez** [comment]
@aetsai is the issue still happening with @gfirem solution?
